const mongoose = require("mongoose");
const { Schema, model } = mongoose;
const opts = { timestamps: true };

const User = model("User", new Schema({
  name: { type: String, required: true, trim: true }, email: { type: String, required: true, unique: true, lowercase: true },
  phone: String, password: { type: String, required: true, select: false }, role: { type: String, enum: ["customer", "worker", "admin"], default: "customer" },
  avatar: String, isVerified: { type: Boolean, default: false }, status: { type: String, enum: ["active", "inactive", "blocked"], default: "active" },
  favorites: [{ type: Schema.Types.ObjectId, ref: "Service" }], refreshToken: { type: String, select: false }, resetToken: { type: String, select: false }, resetTokenExpires: { type: Date, select: false }, lastLoginAt: Date, dateOfBirth: Date, gender: String
}, opts));
const Category = model("Category", new Schema({ name: { type: String, required: true, unique: true }, slug: { type: String, required: true, unique: true }, icon: String, image: String, commission: { type: Number, default: 20 }, active: { type: Boolean, default: true } }, opts));
const serviceSchema = new Schema({ name: { type: String, required: true }, slug: { type: String, required: true, unique: true }, category: { type: Schema.Types.ObjectId, ref: "Category", required: true }, description: String, image: String, price: { type: Number, required: true }, discountedPrice: Number, duration: Number, rating: { type: Number, default: 4.7 }, bookings: { type: Number, default: 0 }, included: [String], excluded: [String], faqs: [{ question: String, answer: String }], cancellationPolicy: String, active: { type: Boolean, default: true } }, opts);
serviceSchema.index({ name: "text", description: "text" });
const Service = model("Service", serviceSchema);
const Worker = model("Worker", new Schema({ user: { type: Schema.Types.ObjectId, ref: "User", required: true, unique: true }, bio: String, experience: Number, skills: [String], services: [{ type: Schema.Types.ObjectId, ref: "Service" }], serviceAreas: [String], languages: [String], rating: { type: Number, default: 0 }, completedJobs: { type: Number, default: 0 }, verificationStatus: { type: String, enum: ["draft","pending", "approved", "rejected", "suspended", "blocked"], default: "draft" }, profileCompleted:{type:Boolean,default:false},documents:[{type:{type:String,enum:["aadhaar","pan","driving_license","certificate","address_proof","other"]},number:String,url:{type:String,required:true},publicId:String,status:{type:String,enum:["pending","verified","rejected"],default:"pending"},note:String}],submittedAt:Date,reviewedAt:Date,reviewedBy:{type:Schema.Types.ObjectId,ref:"User"},rejectionReason:String, available: { type: Boolean, default: false }, workingHours: { start: String, end: String }, maxDailyBookings: { type: Number, default: 5 }, bankDetails: { accountName: String, accountNumber: String, ifsc: String } }, opts));
const Address = model("Address", new Schema({ customer: { type: Schema.Types.ObjectId, ref: "User", required: true }, fullName: String, phone: String, line: String, landmark: String, city: String, state: String, country: { type: String, default: "India" }, postalCode: String, latitude: Number, longitude: Number, type: { type: String, enum: ["home", "work", "other"], default: "home" }, isDefault: Boolean }, opts));
const Booking = model("Booking", new Schema({ bookingId: { type: String, unique: true }, customer: { type: Schema.Types.ObjectId, ref: "User", required: true }, worker: { type: Schema.Types.ObjectId, ref: "Worker" }, service: { type: Schema.Types.ObjectId, ref: "Service", required: true }, address: { type: Schema.Types.ObjectId, ref: "Address", required:true }, scheduledAt: { type: Date, required: true }, paymentMethod:{type:String,enum:["cod","razorpay"],required:true}, status: { type: String, enum: ["pending", "accepted", "worker_assigned", "on_the_way", "arrived", "service_started", "service_completed", "payment_completed", "closed", "rejected", "cancelled", "rescheduled", "refund_requested", "refunded", "disputed"], default: "pending" }, paymentStatus: { type: String, enum: ["pending", "processing", "successful", "failed", "refunded", "partially_refunded"], default: "pending" }, pricing: { servicePrice: Number, additionalCharges: { type: Number, default: 0 }, discount: { type: Number, default: 0 }, tax: Number, total: Number, commission: Number, workerEarning: Number }, coupon: String, timeline: [{ status: String, at: { type: Date, default: Date.now }, note: String }] }, opts));
const Coupon = model("Coupon", new Schema({ code: { type: String, unique: true, uppercase: true }, type: { type: String, enum: ["fixed", "percentage"], default: "percentage" }, value: Number, minOrder: Number, maxDiscount: Number, usageLimit: Number, used: { type: Number, default: 0 }, startsAt: Date, endsAt: Date, active: { type: Boolean, default: true } }, opts));
const Review = model("Review", new Schema({ booking: { type: Schema.Types.ObjectId, ref: "Booking", unique: true }, customer: { type: Schema.Types.ObjectId, ref: "User" }, worker: { type: Schema.Types.ObjectId, ref: "Worker" }, rating: { type: Number, min: 1, max: 5 }, quality: Number, professionalism: Number, behaviour: Number, timeliness: Number, comment: String, status: { type: String, default: "published" } }, opts));
const Complaint = model("Complaint", new Schema({ booking: { type: Schema.Types.ObjectId, ref: "Booking" }, customer: { type: Schema.Types.ObjectId, ref: "User" }, category: String, description: String, status: { type: String, enum: ["created", "admin_review", "worker_response", "investigation", "resolved", "closed"], default: "created" }, resolution: String }, opts));
module.exports = { User, Category, Service, Worker, Address, Booking, Coupon, Review, Complaint };
