require("dotenv").config();
const bcrypt=require("bcryptjs"),connectDB=require("./config/dbConfig");
const {User,Category,Service,Worker,Address,Booking,Coupon,Review,Complaint}=require("./model");
const {Payment,Earning,Payout,Notification,ServicePackage,Referral,Warranty,PlatformSetting,AuditLog,Availability,CancellationPolicy}=require("./model/platformModels");
const rows=[["AC Services","Wind","AC General Service",499],["Cleaning","Sparkles","Full Home Cleaning",1999],["Plumbing","Wrench","Plumber Visit",299],["Electrical","Zap","Electrician Visit",249],["Beauty & Salon","Scissors","Salon at Home",799],["Pest Control","Shield","General Pest Control",1099],["Painting","Paintbrush","Room Painting",2999],["Carpentry","Hammer","Carpenter Visit",349],["Appliance Repair","Cog","Washing Machine Repair",599],["Home Maintenance","House","Annual Home Checkup",2499]];
const wipe=[User,Category,Service,Worker,Address,Booking,Coupon,Review,Complaint,Payment,Earning,Payout,Notification,ServicePackage,Referral,Warranty,PlatformSetting,AuditLog,Availability,CancellationPolicy];
(async()=>{await connectDB();await Promise.all(wipe.map(m=>m.deleteMany({})));const pw=await bcrypt.hash("Password@123",12);const admin=await User.create({name:"HomeServe Admin",email:"admin@homeserve.test",phone:"9000000001",password:pw,role:"admin",isVerified:true});const customer=await User.create({name:"Shirshak Dutta",email:"customer@homeserve.test",phone:"9800000000",password:pw,role:"customer",isVerified:true});
const cats={},services=[];for(const [cat,icon,name,price] of rows){cats[cat]??=await Category.create({name:cat,slug:cat.toLowerCase().replace(/[^a-z0-9]+/g,"-"),icon,commission:20});services.push(await Service.create({name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),category:cats[cat]._id,price,discountedPrice:Math.round(price*.9),description:`Verified professionals for ${name.toLowerCase()} with transparent pricing and service warranty.`,duration:60,rating:+(4.6+Math.random()*.3).toFixed(1),bookings:100+Math.floor(Math.random()*700),included:["Professional inspection","Labour and standard tools","Service warranty"],excluded:["Replacement parts","Major additional work"],faqs:[{question:"Is the professional verified?",answer:"Yes, all HomeServe+ professionals are verified."}],cancellationPolicy:"Free cancellation more than 24 hours before the appointment."}));}
const workers=[];for(const [i,name] of ["Raj Kumar","Anita Sharma","Imran Ali","Pooja Das","Vikram Singh"].entries()){const u=await User.create({name,email:`${name.toLowerCase().replace(" ",".")}@homeserve.test`,phone:`990000000${i}`,password:pw,role:"worker",isVerified:true});const pending=i===4;const w=await Worker.create({user:u._id,bio:"Experienced HomeServe+ professional committed to safe, high-quality service.",experience:3+i,skills:["Inspection","Repair","Customer service"],services:services.slice(i%3,i%3+5).map(s=>s._id),serviceAreas:["Kolkata","Salt Lake","New Town"],languages:["English","Hindi","Bengali"],bankDetails:{accountName:name,accountNumber:`123456789${i}`,ifsc:"HDFC0001234"},documents:[{type:"aadhaar",number:`XXXX-XXXX-100${i}`,url:"https://res.cloudinary.com/demo/image/upload/sample.jpg",status:pending?"pending":"verified"},{type:"certificate",number:`CERT-${i+1}`,url:"https://res.cloudinary.com/demo/image/upload/sample.jpg",status:pending?"pending":"verified"}],profileCompleted:true,submittedAt:new Date(),verificationStatus:pending?"pending":"approved",available:!pending,completedJobs:pending?0:180+i*87,rating:pending?0:+(4.6+i*.07).toFixed(1),workingHours:{start:"10:00",end:"19:00"}});workers.push(w);await Availability.create({worker:w._id,workingDays:[1,2,3,4,5,6],startTime:"10:00",endTime:"19:00",breaks:[{start:"14:00",end:"15:00"}],maxDailyBookings:5});}
const address=await Address.create({customer:customer._id,fullName:customer.name,phone:customer.phone,line:"Sector V, Salt Lake",landmark:"Near College More",city:"Kolkata",state:"West Bengal",postalCode:"700091",type:"home",isDefault:true,latitude:22.5726,longitude:88.3639});
for(let i=0;i<18;i++){const service=services[i%services.length],worker=workers[i%4],base=service.discountedPrice,tax=+(base*.18).toFixed(2),commission=+(base*.2).toFixed(2),status=i<12?"closed":i<15?"service_completed":"accepted";const booking=await Booking.create({bookingId:`HS-2609${String(i+1).padStart(4,"0")}`,customer:customer._id,worker:worker._id,service:service._id,address:address._id,scheduledAt:new Date(Date.now()+(i-13)*864e5),paymentMethod:i%3===0?"cod":"razorpay",status,paymentStatus:i<15?"successful":"pending",pricing:{servicePrice:base,discount:0,tax,total:base+tax,commission,workerEarning:base-commission},timeline:[{status:"pending"},{status}]});if(i<15){await Payment.create({booking:booking._id,customer:customer._id,transactionId:`pay_demo_${i+1}`,orderId:`order_demo_${i+1}`,amount:base+tax,method:i%2?"UPI":"Card",gatewayStatus:"captured",status:"successful",paidAt:new Date()});await Earning.create({worker:worker._id,booking:booking._id,grossAmount:base,discount:0,commission,netAmount:base-commission,paymentStatus:"successful",payoutStatus:i<8?"paid":"pending"});}if(i<5)await Review.create({booking:booking._id,customer:customer._id,worker:worker._id,rating:5-i%2,quality:5,professionalism:5,behaviour:5,timeliness:4,comment:"Professional, punctual and excellent service."});}
await Promise.all([Coupon.create({code:"WELCOME20",type:"percentage",value:20,minOrder:299,maxDiscount:300,usageLimit:1000,used:84,startsAt:new Date("2025-01-01"),endsAt:new Date("2030-12-31")}),Coupon.create({code:"HOME100",type:"fixed",value:100,minOrder:999,maxDiscount:100,usageLimit:500,used:62,startsAt:new Date("2025-01-01"),endsAt:new Date("2030-12-31")}),Payout.create({worker:workers[0]._id,amount:8200,status:"pending"}),Complaint.create({booking:(await Booking.findOne())._id,customer:customer._id,category:"Payment issue",description:"Payment charged twice",status:"investigation"}),ServicePackage.create({name:"AC Care Package",description:"Three AC services valid for six months",services:[services[0]._id],price:1299,validityDays:180}),Referral.create({referrer:customer._id,code:"SHIRSHAK250",credit:250,status:"active"}),Notification.create({recipient:customer._id,role:"customer",type:"booking_reminder",title:"Service tomorrow",message:"Raj Kumar is scheduled for your AC service tomorrow at 10:00 AM."}),CancellationPolicy.create({name:"Standard cancellation",rules:[{hoursBefore:24,refundPercent:100,fee:0},{hoursBefore:12,refundPercent:50,fee:0},{hoursBefore:0,refundPercent:0,fee:199}]})]);
for(const [key,value,group] of [["platformName","HomeServe+","branding"],["currency","INR","finance"],["taxPercent",18,"finance"],["defaultCommission",20,"finance"],["autoAssignment",true,"booking"],["minimumBooking",199,"booking"],["supportEmail","support@homeserve.test","contact"]])await PlatformSetting.create({key,value,group});
console.log("Seeded complete demo\nAdmin: admin@homeserve.test\nCustomer: customer@homeserve.test\nWorker: raj.kumar@homeserve.test\nPassword: Password@123\nCoupon: WELCOME20");process.exit(0)})().catch(e=>{console.error(e);process.exit(1)});
